# Generated by Django 4.0 on 2021-12-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_name_book_narx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='narx',
            new_name='name',
        ),
    ]
