# Generated by Django 4.0 on 2021-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_narx_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='fakaferi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
