# Generated by Django 4.0 on 2021-12-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_libuser_fakaferi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libuser',
            old_name='name',
            new_name='jerjero',
        ),
    ]
