# Generated by Django 4.0 on 2021-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_name_libuser_jerjero'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='rasmlar'),
        ),
    ]
